# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 101b45c06e3c9f2a4ce0897a30bc41f140cc551b966e2ae93cd2d288e0acfce412014a120726bd6e244e22c43b722cbea042967011124c0c4a5b4ab5c3eb341e

test:
  secret_key_base: 68af7a8b30831f784c1bcfb9ed42fb267cb9326c067fb8b1c4a820564b363e11be0408b453db14e5bb9b129f7cb6a720d178d9d906c6e917bb0da9624d522d5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
